### ISSUE TITLE
Fail to build: run go mod vendor

### ISSUE THREAD

**Issue by tami5** [tweag/gomod2nix#7]
**Describe the bug**

Try to adding gomod2nix with using flake result in error:

```
error: builder for '/nix/store/nb278di7gkia1gg74w93nxvd7cj9pihd-gomod2nix-0.1.drv' failed with exit code 1;
       last 10 log lines:
       > building
       > Building subPackage ./.
       > go: inconsistent vendoring in /build/source:
       >         github.com/BurntSushi/toml@v0.3.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >  github.com/orivej/go-nix@v0.0.0-20180830055821-dae45d921a44: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >        github.com/sirupsen/logrus@v1.7.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >  golang.org/x/mod@v0.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >    golang.org/x/tools@v0.0.0-20191119224855-298f0cb1881e: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       >
       > run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
       For full logs, run 'nix log /nix/store/nb278di7gkia1gg74w93nxvd7cj9pihd-gomod2nix-0.1.drv'.
error: 1 dependencies of derivation '/nix/store/w39zbwbbmf2jhh6qjh4x6726lxxnyzi8-nix-shell-env.drv' failed to build

```

**To Reproduce**
Steps to reproduce the behavior.

In flake.nix:

```nix
inputs.go2nix.url = "github:tweag/gomod2nix";
....

....
      {
        devShell."${system}" = import ./shell.nix {
          inherit pkgs attrs inputs system;
        };
```

in shell.nix

```nix
{ pkgs ? import <nixpkgs> {}, attrs, inputs, system, ... }:
pkgs.mkShell {
  buildInputs = with pkgs; [
    go
    inputs.go2nix.defaultPackage.${system}
  ];
  shellHook = with attrs; ''
    echo 'Entering ${pname}'
  '';
}
```
**Expected behavior**

Build okay.

**Environment**
 - OS name + version: nxios
 - Version of the code: master

**Additional context**

**Comment by sarahhodne** [comment]
I had this problem too, looks like gomod2nix depends on nixpkgs-unstable, so switching to that (I'm using [niv](https://github.com/nmattia/niv), so `niv update nixpkgs -b nixos-unstable` did what I needed) fixed it for me.

**Comment by snawaz** [comment]
> I had this problem too, looks like gomod2nix depends on nixpkgs-unstable, so switching to that (I'm using [niv](https://github.com/nmattia/niv), so `niv update nixpkgs -b nixos-unstable` did what I needed) fixed it for me.

Why does it use `nixpkgs-unstable`? Is that (and this `gomod2nix`) safe to use?

**Comment by voidus** [comment]
I've looked into this a bit, and with my limited go and nix knowledge I found out the following:

- This package uses the `vendor` directory to make go use the nix-provided dependencies, so disabling it would somewhat defeat the purpose
- Go expects `modules.txt` file in `vendor`, which this package doesn't provide.

@sarahhodne I'm somewhat confused it works for you. Does your project maybe have no dependencies at all? That's the only thing that would makes sense to me right now.

Going forward, I think that we need to generate this modules.txt file somehow. Again, two ideas:
- Call `go mod vendor` and throw away everything except `modules.txt`. This seems brittle to me, because we're running the risk of `modules.txt` and the actual vendored modules not fitting together.
- Generate `modules.txt` from the nix inputs. I couldn't find any documentation about this file.

As far as I can tell, we should be able to piece `modules.txt` together from the information in `gomod2nix.toml` (for the versions and the complete list) and `go.mod` (for determining which dependency is explicit).

I hope that helps.

For reference, here's the `vendor/modules.txt` `go mod vendor` generates on my system.

```
# github.com/BurntSushi/toml v0.3.1
## explicit
github.com/BurntSushi/toml
# github.com/orivej/e v0.0.0-20180728214217-ac3492690fda
github.com/orivej/e
# github.com/orivej/go-nix v0.0.0-20180830055821-dae45d921a44
## explicit
github.com/orivej/go-nix/nix/eval
github.com/orivej/go-nix/nix/parser
# github.com/sirupsen/logrus v1.7.0
## explicit
github.com/sirupsen/logrus
# golang.org/x/mod v0.3.0
## explicit
golang.org/x/mod/internal/lazyregexp
golang.org/x/mod/modfile
golang.org/x/mod/module
golang.org/x/mod/semver
# golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
golang.org/x/sys/unix
golang.org/x/sys/windows
# golang.org/x/tools v0.0.0-20191119224855-298f0cb1881e
## explicit
golang.org/x/tools/go/vcs
# golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898
golang.org/x/xerrors
golang.org/x/xerrors/internal
```

**Comment by Mic92** [comment]
For flakes user this helps: https://github.com/tweag/gomod2nix/pull/12

**Comment by adisbladis** [comment]
This issue has long since hit Nix stable channels.
